#!/bin/bash
function upfind() {
    pushd $PWD > /dev/null
    while [[ $PWD != / ]] ; do
        find "$PWD" -maxdepth 1 -name "$1"
        cd ..
    done
    popd > /dev/null
}

function evil_git_dirty {
  [[ $(git diff --shortstat 2> /dev/null | tail -n1) != "" ]] && echo "*"
}

PROJNAME=Rql
SLNFILE=$(upfind $PROJNAME.sln)
if [[ $SLNFILE == "/" ]]; then {
    echo "Cannot find solution " $PROJNAME.sln
    exit
}; fi
SLNDIR=$(dirname $SLNFILE)
pushd $SLNDIR
if [[ $(evil_git_dirty) == "*" ]]; then {
    echo "You have uncommitted changes! Please stash or commit them first."
    exit
}; fi
vamper -u
git add . 
git commit -F scratch/$PROJNAME.version.txt
popd